Sniff out internal failures in another way in CompilationTestHelper.
I had a mysteriously failing test (failing with no diagnostics) which was failing with a `NoSuchMethodError` in the constructor.

I'm not at all sure this is the right fix!

PiperOrigin-RevId: 567605302