UnusedException: consistent with UnnamedVariable
A false positive [`UnusedException`](https://errorprone.info/bugpattern/UnusedException) can be suppressed by naming the caught exception `/unused.*/`. The recently added [`UnnamedVariable`](https://errorprone.info/bugpattern/UnnamedVariable), in the meantime, wants deliberately unused variables to be unnamed with the Java 22 `_` character, putting the two checks at odds. Teach `UnusedException` to also accept `_` as a suppression mechanism.

Fixes #5459

COPYBARA_INTEGRATE_REVIEW=https://github.com/google/error-prone/pull/5459 from commonquail:unusedex-unnamed ac5edf75075cf4efa57a014a8d41781df8f08f70
PiperOrigin-RevId: 862308754