error-prone can now output multiple suggested fixes.  Also remove Fix.NO_FIX since that has been effectively replaced by an empty list of fixes.
Multiple fixes are now presented in the diagnostic message when used as a
compiler, joined by 'or'.  They look like:
StringEqualityPositiveCases.java:28: error: [StringEquality] String comparison using reference equality instead of value equality
retVal = (x == y);
^
(see http://code.google.com/p/error-prone/wiki/StringEquality)
Did you mean 'retVal = (Objects.equals(x, y));' or 'retVal = (x.equals(y));'?

-------------
Created by MOE: http://code.google.com/p/moe-java
MOE_MIGRATED_REVID=76989307