Delete `SourceVersion.supportsEffectivelyFinal`.
Error Prone is [requiring users to run javac from JDK 21 or higher](https://github.com/google/error-prone/issues/4867), and JDK 21 does not support `-source` values below 8:

```
$ ~/jdk-21.0.2/bin/javac -source 7 Foo.java
warning: [options] bootstrap class path not set in conjunction with -source 7
error: Source option 7 is no longer supported. Use 8 or later.
```
PiperOrigin-RevId: 810107634