Don't compile test inputs twice
This was added in unknown commit, but since unknown commit Error Prone doesn't run
on compilations that contain errors, so if there are any diagnostics we'll just
skip running Error Prone for free and the test will fail with unexpected javac
diagnostics, e.g.:

```
1) extendsAutoValue_goodNoSuperclass(com.google.errorprone.bugpatterns.ExtendsAutoValueTest)
java.lang.AssertionError: Saw unexpected error on line 1. All errors:
/google3/TestClass.java:1: error: '{' expected
public class TestClass }
                      ^
        at org.junit.Assert.fail(Assert.java:89)
        at com.google.errorprone.DiagnosticTestHelper.assertHasDiagnosticOnAllMatchingLines(DiagnosticTestHelper.java:348)
```

PiperOrigin-RevId: 348568488