Add a checker that checks to see if Arrays.fill(Object[], Object) is called with incompatible types.
RELNOTES: New error: ArrayFillIncompatibleType. Triggered when
Arrays.fill(Object[], Object) is called when the second argument can't safely
be inserted into the array parameter (e.g. storing Integer into a String[]).

-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=167782668