Initial implementation of a com.sun.source.util.Plugin
This allows Error Prone to be used as a javac plugin (instead of a
wrapper) via the plugin API that was added in 8:
https://docs.oracle.com/javase/8/docs/jdk/api/javac/tree/com/sun/source/util/Plugin.html

Demo:

```
javac -J-Xbootclasspath/p:javac-9-dev-r3297-3.jar \
  -processorpath error_prone_ant-2.0.18-SNAPSHOT.jar \
  -Xplugin:ErrorProne Test.java
...
ShortSet.java:8: error: [CollectionIncompatibleType] Argument 'i - 1' should not be passed to this method; its type int is not compatible with its collection's type argument Short
      s.remove(i - 1);
              ^
    (see http://errorprone.info/bugpattern/CollectionIncompatibleType)
```

See #535

MOE_MIGRATED_REVID=148835033